#BashAddShebang
export TERM=xterm

	echo -e "               _______								"
	echo -e "               |     |								"
	echo -e "               |     |								"
	echo -e "               x-----x								"
	echo -e "               x     x								"
	echo -e "               x     x								"
	echo -e "               x     x								"
	echo -e "               x=====x								"
	echo -e "               x     x								"
	echo -e "               x     x								"
	echo -e "               x     x								"
	echo -e "               x     x								"
	echo -e "               x     x								"
	echo -e "       xxxxxxx xxxxxxx xxxxxxx xxxxxxx				"
	echo -e "       X     X X     X X     X X     X				"
	echo -e "       X     X X     X X     X X     X				"
	echo -e "       X     X X     X X     X X     X				"
	echo -e "       X     X X     X X     X X     X				"
	echo -e "       X     X X     X X     X X     X				"
	echo -e "       X     X X     X X     X X     X				"
	echo -e "       X     X X     X X     X X     X				"
	echo -e "       X     X X     X X     X X     X				"
	echo; echo; echo;

	echo -e "Quinoa: A multipurpose word enjoyed deeply be Drew Quinn and friends. \n"
	echo -e "Kale: When consumed in large quantities, as it should be, is often accompanied by perfuse sweating known as 'the kale sweats' (as per Bart Mosele)\n"
	echo -e "Slogans:"
	echo -e "Tofu! It's not just for breakfast anymore."
	echo -e "Soy! It does the body good.\n"
	echo -e "Copy right: Drew Quinn, Fred Lowe. 1996\n\n"
	echo -e "Please note that your command: '$Command' was not found. Try 'vm help' if you are not competent. \n"
